/**
 * Learn tier: Custom slash command generation.
 *
 * Generates .claude/commands/*.md workflow files from recurring
 * pattern detections, encoding corrected workflows so the agent
 * follows a structured process instead of looping.
 */

import type { Detection } from "../types.js";

/** A proposed custom slash command. */
export interface CommandProposal {
  /** Pattern that triggered this proposal. */
  pattern_name: string;
  /** Command name (becomes /command-name in Claude Code). */
  name: string;
  /** Human-readable description. */
  description: string;
  /** Markdown content for the command file. */
  content: string;
  /** File path relative to project root. */
  file_path: string;
  /** Stable key for deduplication. */
  dedup_key: string;
}

// ---------------------------------------------------------------------------
// Command templates
// ---------------------------------------------------------------------------

type CommandTemplate = (detection: Detection) => CommandProposal;

const COMMAND_TEMPLATES: Record<string, CommandTemplate> = {
  circular_reasoning: () => ({
    pattern_name: "circular_reasoning",
    name: "research",
    description: "Structured research workflow to avoid circular search loops",
    content: [
      "# /research — Structured Research Workflow",
      "# Auto-generated by Varpulis Agent Runtime (circular_reasoning pattern)",
      "",
      "Follow this exact sequence:",
      "",
      "1. Formulate a single, specific search query",
      "2. Search once. Read the top 2 results.",
      '3. Extract the key facts into a scratchpad (use Write to create .tmp/research_notes.md)',
      "4. If the answer is sufficient, proceed to the final output",
      "5. If not, formulate a NEW query (different keywords) — do NOT repeat the previous query",
      "6. Maximum 3 search rounds. After round 3, produce the best answer you have.",
      "",
      "Do NOT loop between search and read without writing notes.",
      "Do NOT re-search the same query with identical parameters.",
    ].join("\n"),
    file_path: ".claude/commands/research.md",
    dedup_key: "cmd_research",
  }),

  stuck_agent: () => ({
    pattern_name: "stuck_agent",
    name: "unstick",
    description: "Workflow to break out of unproductive loops",
    content: [
      "# /unstick — Break Out of Unproductive Loops",
      "# Auto-generated by Varpulis Agent Runtime (stuck_agent pattern)",
      "",
      "You appear to be stuck. Follow this recovery sequence:",
      "",
      "1. Stop all current tool calls",
      "2. Summarize what you have accomplished so far",
      "3. Identify the specific blocker — what is preventing progress?",
      "4. List 3 alternative approaches you haven't tried",
      "5. Pick the most promising alternative and try it",
      "6. If still stuck after 5 more steps, ask the user for guidance",
      "",
      "Do NOT continue the same approach that has not been working.",
    ].join("\n"),
    file_path: ".claude/commands/unstick.md",
    dedup_key: "cmd_unstick",
  }),

  error_spiral: () => ({
    pattern_name: "error_spiral",
    name: "debug",
    description: "Structured debugging workflow to break error spirals",
    content: [
      "# /debug — Structured Debugging Workflow",
      "# Auto-generated by Varpulis Agent Runtime (error_spiral pattern)",
      "",
      "Multiple tool calls are failing. Follow this diagnostic sequence:",
      "",
      "1. Stop retrying the failing operation",
      "2. Read the last 3 error messages carefully",
      "3. Identify the root cause — is it a missing dependency, wrong path, permission issue, or logic error?",
      "4. Fix the root cause before retrying the original operation",
      "5. If the root cause is unclear, check related files and configuration",
      "6. If still failing after the fix, explain the situation to the user",
      "",
      "Do NOT retry the same command hoping for a different result.",
    ].join("\n"),
    file_path: ".claude/commands/debug.md",
    dedup_key: "cmd_debug",
  }),

  IntentStall: () => ({
    pattern_name: "IntentStall",
    name: "execute",
    description: "Force immediate tool execution without narration",
    content: [
      "# /execute — Immediate Execution Mode",
      "# Auto-generated by Varpulis Agent Runtime (IntentStall pattern)",
      "",
      "Switch to immediate execution mode:",
      "",
      "- Do NOT describe what you are about to do",
      "- Do NOT explain your reasoning before acting",
      "- Emit tool_use blocks directly",
      "- Only explain AFTER the action is complete if the result needs context",
      "",
      "This mode is active for the remainder of this task.",
    ].join("\n"),
    file_path: ".claude/commands/execute.md",
    dedup_key: "cmd_execute",
  }),
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate a command proposal from a detection.
 * Returns null if no command template exists for this pattern.
 */
export function proposeCommand(detection: Detection): CommandProposal | null {
  const template = COMMAND_TEMPLATES[detection.pattern_name];
  if (!template) return null;
  return template(detection);
}

/**
 * Check if a command already exists by looking for the dedup key
 * in existing command file names or a list of known command names.
 */
export function isCommandDuplicate(
  proposal: CommandProposal,
  existingCommandNames: string[],
): boolean {
  return existingCommandNames.some(
    (name) =>
      name === proposal.name ||
      name === `${proposal.name}.md` ||
      name === proposal.file_path,
  );
}
